name: Trivy Nightly Scan
on:
  schedule:
    - cron: '0 2 * * 5'  # Run at 2AM UTC on every Friday

permissions: read-all
jobs:
  nightly-scan:
    name: Trivy Scan nightly
    strategy:
      fail-fast: false
      matrix:
        # It will test for only the latest version as older version is not maintained
        versions: [latest]
    permissions:
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2  # master
        with:
          image-ref: 'docker.io/coredns/coredns:${{ matrix.versions }}'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@e2b3eafc8d227b0241d48be5f425d47c2d750a13  # v3.26.10
        with:
          sarif_file: 'trivy-results.sarif'
